backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "images/"
publish_mode: editorial_workflow


collections:
  - name: "pages"
    label: "Pages"
    folder: "/"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "pages"}
      - {label: "Title", name: "title"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "entries"
    label: "Entries"
    folder: "_entries/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "detail", required: false}
      - {label: "Name", name: "title", widget: "string"}
      - { label: "English Name", name: "english_name", widget: "string"}
      - {label: "Byline (dates and locations)", name: "byline", widget: "string", required: false}
      - {label: "Full Length Image", name: "full_image", widget: "image", required: false}
      - {label: "Folded Image (ryan reynolds)", name: "folded_image", widget: "image", required: false}
      - {label: "Historical Image", name: "historical_image", widget: "image", required: false}
      - {label: "Teaching", name: "teaching", widget: "markdown", required: false}
      - {label: "Blessing", name: "blessing", widget: "markdown", required: false}
      - {label: "Youtube Link", name: "youtube_link", widget: "string", required: false}
      - {label: "Description", name: "body", widget: "markdown", required: false}
